### ISSUE TITLE
ATmega32A attempt

### ISSUE THREAD

**Issue by Wynadorn** [jdolinay/avr_debug#23]
Hey,

I've attempted to port the stub to the ATmega32A.
By which I mean I've changed a couple of register values.

It's not working however, this is GDB's output

```
wyn@hyron:~/dbg$ sudo avr-gdb main.elf -tui
Reading symbols from main.elf...done.
(gdb) target remote /dev/ttyS3
Remote debugging using /dev/ttyS3
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
Remote replied unexpectedly to 'vMustReplyEmpty': timeout
(gdb)
```

As soon as the `target remote /dev/ttyS3` line has been executed the chip's execution halts.
Do any of these error messages ring a bell for you?
It might be something really obvious as I'm definitely still a beginner when it comes to MCU's.

I'm using a bare Atmega32A connected though a FTDI FT232RL
`VCC` to `VCC`
`GND` to `GND`
`RX` to `(TXD) PD1`
`TX` to `(RDX) PD0`
`DTR` & `CTS` unconnected

**Comment by jdolinay** [comment]
Hey, 

Unfortunately the error messages do not tell anything specific, just that the GDB cannot establish communication with the debugger stub in the MCU. This can be for many reasons including simple ones like missing call to debug_init() in the debugged program or wrong baudrate, but it can also be any problem in the code of the stub. 
If you haven't tried it yet, you could first write simple program which will receive and send data from serial line, to make sure that your routines for the UART are working and that the hardware setup is OK. 

I think porting the stub may be quite difficult and the result not worth it. The basic version with breakpoints in RAM which you will get has several limitations and is not too useful for debugging real projects. With the flash breakpoints it becomes much better but to implement that you would have to dig even deeper into the stub code... 

I'd say writing this stub made sense for the standard Arduino boards because this allows many people to debug their programs (at least a little). But if you are doing some project with custom board and a different MCU and need a debugger, it may be much quicker and easier to buy a hardware debugger (debug probe) and debug it the "native" way, using the debug circuitry built into the MCU.
