### ISSUE TITLE
Simpler, but no GUI for gdb (but command line avr-gdb.exe works)

### ISSUE THREAD

**Issue by JungHong** [jdolinay/avr_debug#4]
On page 20, Section 1.7 of "Arduino Debugger", it says to let you know if there is a simpler set up.

I ran across 'Sloeber V4.2' at http://eclipse.baeyens.it/  It is Eclipse with Arduino.  I was able to download it and immediately write a test program, including the debug codes on page 29 and page 40; upload them; and execute.

It does not have a Gdb front end.

I was able to use command line avr-gdb.exe version 7.8 from Atmel Studio 7.0 and separately avr-gdb.exe version 7.11 from SysGCC to connect to the above mentioned test programs executing on Uno.  The gdb experience is as expected, confirming that AVR_DEBUG functions as expected. Since Windows COM has issues,  I had to use COMbyTCP.exe

As an aside, I could not execute the avr-gdb.exe that comes with sloeber V4.2 ... it errors because of dll problems.

Since Sloeber is Eclipse, would it be possible to add the GDB Hardware Debugging launch configuration, similar to Section 1.6 of your user guide,  to Sloeber ?

Then, all your goals would be met and it would be simpler for the user.

**Comment by jdolinay** [comment]
Thanks for the tip. I tried the Sloeber some time ago and it looks interesting but there are some downsides. As I understand it the author first developed Eclipse plugin for Arduino and now created standalove application based on eclipse called Sloeber. I think Sloeber does not contain the complete eclipse "API", so it wouldn't be easy to add the GDB Hardware debugging to it. Probably you would have to create your own version of Sloeber from the sources. I am not an expert on eclipse development, so this seems complicated.

A better solution based on eclise could be Eclipse C++ IDE for  Arduino - https://marketplace.eclipse.org/content/eclipse-c-ide-arduino. This is complete Eclipse IDE with arduino support.

Yet another solution which seems promising to me now is Visual Studio Code with Arduino extension. This makes it easy to build Arduino programs including management of the libraries etc. and it also supports Gdb debugging.

As to the error executing avr-gdb.exe that comes with sloeber it is probably because Sloeber takes the Arduino build environment which contains this broken avr-gdb. I summarized my experience with this on page 8 in the Arduino debugger doc in chapter Problems with GDB (avr-gdb) included with Arduino.
