### ISSUE TITLE
no elf

### ISSUE THREAD

**Issue by geetee24** [jdolinay/avr_debug#42]
see pic
![IMG004](https://user-images.githubusercontent.com/6679119/147684227-b8988292-359f-425c-b5af-3b7c0863a6df.jpg)

**Comment by jdolinay** [comment]
The root cause is probably #40, the program is not built, that is why the .elf file does not exist. There should be build errors before you get to this point, such as the one in #41. 
If the program builds without error, then it is also possible that the name or location of the output file is different. Check if you have the "output": ".\\build", line in your arduino.json.
